spring:
  datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}

  jpa:
    hibernate:
      ddl-auto: update
      physical_naming_strategy: "io.micronaut.data.hibernate.naming.DefaultPhysicalNamingStrategy"
    show-sql: true

  liquibase:
    change-log: db/changelog/db.changelog.xml
    enabled: true
    drop-first: true

  server:
    url:${server.url}

