spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog.xml
    drop-first: true

server:
  port: 8081
  error:
    whitelabel:
      enabled: false


